export ZSH=/usr/share/oh-my-zsh
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
#ZSH_THEME='theOne'
ZSH_THEME="agnoster"
alias ll='ls -la --color=auto'
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
